import { useEffect, useState } from "react";
import { Bike, UserRound } from "lucide-react";
import { hasSupabaseConfig, invokeApi, listRecords } from "../lib/data";

export default function CustomerVehicleAssignmentsView() {
  const [customers, setCustomers] = useState([]); const [bikes, setBikes] = useState([]);
  const [customerId, setCustomerId] = useState(""); const [bikeId, setBikeId] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { const [customerRows, bikeRows] = await Promise.all([listRecords("customers", { pageSize: 1000 }), listRecords("bikes", { pageSize: 1000 })]); if (customerRows.error || bikeRows.error) return setMessage((customerRows.error || bikeRows.error).message); setCustomers(customerRows.data || []); setBikes((bikeRows.data || []).filter(bike => !bike.customer_id)); };
  useEffect(() => { if (hasSupabaseConfig) load(); }, []);
  const assign = async () => { if (!customerId || !bikeId) return setMessage("Choose an existing customer and an available tracker product."); setSaving(true); const result = await invokeApi(`/v1/admin/customers/${encodeURIComponent(customerId)}/vehicles`, { bikeId }); setSaving(false); if (result.error) return setMessage(result.error.message); setMessage("Vehicle assigned. A separate screening and payment record is ready for this customer."); setBikeId(""); load(); };
  return <section className="panel module-table"><div className="panel-heading"><div><h2>Customer vehicle assignments</h2><p>Sell an available tracker product to an existing customer. Each vehicle has its own screening and payment record.</p></div></div><div className="customer-record-form"><div className="customer-form-grid"><label><UserRound size={14}/> Existing customer<select value={customerId} onChange={event => setCustomerId(event.target.value)}><option value="">Choose customer</option>{customers.map(customer => <option key={customer.id} value={customer.id}>{customer.full_name} · {customer.phone || customer.email || "Customer"}</option>)}</select></label><label><Bike size={14}/> Available tracker product<select value={bikeId} onChange={event => setBikeId(event.target.value)}><option value="">Choose tracker</option>{bikes.map(bike => <option key={bike.id} value={bike.id}>{bike.identifier} · {bike.product_type} · KES {Number(bike.payable_amount || 0).toLocaleString()}</option>)}</select></label></div><div className="detail-actions"><button className="button primary" disabled={saving} onClick={assign}><Bike size={15}/>{saving ? "Assigning…" : "Assign vehicle to customer"}</button></div>{message && <p className="import-message">{message}</p>}</div></section>;
}
