import { useEffect, useMemo, useState } from "react";
import { Bike, Search, UserRound } from "lucide-react";
import { hasSupabaseConfig, invokeApi, listRecords } from "../lib/data";

export default function CustomerVehicleAssignmentsView() {
  const [customers, setCustomers] = useState([]); const [bikes, setBikes] = useState([]);
  const [customerId, setCustomerId] = useState(""); const [customerSearch, setCustomerSearch] = useState(""); const [bikeId, setBikeId] = useState(""); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { const [customerRows, bikeRows] = await Promise.all([listRecords("customers", { pageSize: 1000 }), listRecords("bikes", { pageSize: 1000 })]); if (customerRows.error || bikeRows.error) return setMessage((customerRows.error || bikeRows.error).message); setCustomers(customerRows.data || []); setBikes((bikeRows.data || []).filter(bike => !bike.customer_id)); };
  useEffect(() => { if (hasSupabaseConfig) load(); }, []);
  const matches = useMemo(() => customers.filter(customer => `${customer.full_name} ${customer.phone || ""} ${customer.email || ""}`.toLowerCase().includes(customerSearch.trim().toLowerCase())).slice(0, 8), [customers, customerSearch]);
  const selectedCustomer = customers.find(customer => customer.id === customerId);
  const assign = async () => { if (!customerId || !bikeId) return setMessage("Choose an existing customer and an available tracker product."); setSaving(true); const result = await invokeApi(`/v1/admin/customers/${encodeURIComponent(customerId)}/vehicles`, { bikeId }); setSaving(false); if (result.error) return setMessage(result.error.message); setMessage("Vehicle assigned. A separate screening and payment record is ready for this customer."); setBikeId(""); load(); };
  return <section className="panel module-table"><div className="panel-heading"><div><h2>Customer vehicle assignments</h2><p>Find a customer, select the correct record, then assign an available tracker product. Each vehicle has its own screening and payment record.</p></div></div><div className="customer-record-form"><div className="customer-form-grid"><label className="wide"><UserRound size={14}/> Find existing customer<div className="table-search"><Search size={15}/><input value={customerSearch} onChange={event => { setCustomerSearch(event.target.value); setCustomerId(""); }} placeholder="Search by customer name, phone, or email"/></div>{customerSearch && <div className="assignment-search-results">{matches.map(customer => <button type="button" key={customer.id} className={customer.id === customerId ? "assignment-match selected" : "assignment-match"} onClick={() => { setCustomerId(customer.id); setCustomerSearch(customer.full_name); }}><strong>{customer.full_name}</strong><small>{customer.phone || customer.email || "Customer record"}</small></button>)}{!matches.length && <small>No matching customer.</small>}</div>}{selectedCustomer && <small className="assignment-selected">Selected: {selectedCustomer.full_name}</small>}</label><label><Bike size={14}/> Available tracker product<select value={bikeId} onChange={event => setBikeId(event.target.value)}><option value="">Choose tracker</option>{bikes.map(bike => <option key={bike.id} value={bike.id}>{bike.identifier} · {bike.product_type} · KES {Number(bike.payable_amount || 0).toLocaleString()}</option>)}</select></label></div><div className="detail-actions"><button className="button primary" disabled={saving} onClick={assign}><Bike size={15}/>{saving ? "Assigning…" : "Assign vehicle to customer"}</button></div>{message && <p className="import-message">{message}</p>}</div></section>;
}
