import { useEffect, useState } from "react";
import { CheckCircle2, LoaderCircle, ShieldCheck, Wifi, XCircle } from "lucide-react";

const apiBase = `${import.meta.env.VITE_SUPABASE_URL || ""}/functions/v1/api`;
export default function WifiPortal() {
  const [packages, setPackages] = useState([]); const [selected, setSelected] = useState(null); const [phone, setPhone] = useState(""); const [purchase, setPurchase] = useState(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch(`${apiBase}/v1/wifi/packages`, { headers: { apikey: import.meta.env.VITE_SUPABASE_ANON_KEY || "" } }).then((response) => response.json()).then((body) => setPackages(body.packages || [])).catch(() => setMessage("Wi-Fi packages are temporarily unavailable.")); }, []);
  useEffect(() => { if (!purchase?.id || !["pending", "active"].includes(purchase.status)) return undefined; const timer = setInterval(async () => { const result = await fetch(`${apiBase}/v1/wifi/sessions/${purchase.sessionId}`, { headers: { apikey: import.meta.env.VITE_SUPABASE_ANON_KEY || "" } }); const body = await result.json(); if (body.session) setPurchase((current) => ({ ...current, ...body.session })); }, 4000); return () => clearInterval(timer); }, [purchase?.id, purchase?.status, purchase?.sessionId]);
  const buy = async () => { if (!selected || !phone.trim()) return setMessage("Enter the M-Pesa phone number to continue."); setBusy(true); setMessage(""); const idempotencyKey = `wifi-${crypto.randomUUID()}`; try { const response = await fetch(`${apiBase}/v1/wifi/purchase`, { method: "POST", headers: { apikey: import.meta.env.VITE_SUPABASE_ANON_KEY || "", "Content-Type": "application/json", "Idempotency-Key": idempotencyKey }, body: JSON.stringify({ packageId: selected.id, phone, deviceMac: null }) }); const body = await response.json(); if (!response.ok) throw new Error(body.message || "Could not start payment."); setPurchase({ ...body.purchase, sessionId: body.sessionId }); setMessage("Approve the M-Pesa prompt on your phone. Internet activates only after confirmation."); } catch (error) { setMessage(error.message); } finally { setBusy(false); } };
  return <main className="wifi-portal"><header className="wifi-portal-header"><div className="wifi-brand"><span><Wifi size={19} /></span><strong>Jixels Rural Wi-Fi</strong></div><small><ShieldCheck size={14} /> Secure prepaid access</small></header><section className="wifi-hero"><p className="eyebrow">CONNECT LOCALLY</p><h1>Choose your Wi-Fi time</h1><p>Pay securely with M-Pesa. Your access starts only after payment is confirmed.</p></section><section className="wifi-packages">{packages.map((item) => <button className={`wifi-package ${item.is_popular ? "popular" : ""} ${selected?.id === item.id ? "selected" : ""}`} key={item.id} onClick={() => setSelected(item)}><div>{item.is_popular && <span className="wifi-popular">Popular</span>}<h2>{item.name}</h2><strong>KSh {Number(item.price_kes).toLocaleString()}</strong><p>{item.description}</p><small>{item.duration_minutes >= 1440 ? `${item.duration_minutes / 1440} days` : `${item.duration_minutes} minutes`}</small></div><span className="wifi-buy">Buy Now</span></button>)}</section>{selected && !purchase && <section className="wifi-payment"><div><h2>Pay for {selected.name}</h2><p>KSh {Number(selected.price_kes).toLocaleString()} · access for {selected.duration_minutes} minutes</p></div><input value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="M-Pesa number e.g. 0712 345 678" inputMode="tel" /><button className="wifi-action" disabled={busy} onClick={buy}>{busy ? <LoaderCircle className="spin" size={17} /> : "Send M-Pesa prompt"}</button></section>}{purchase?.status === "active" && <section className="wifi-success"><CheckCircle2 size={28} /><div><h2>Internet active</h2><p>Your package is active until {new Date(purchase.expires_at).toLocaleString()}.</p></div></section>}{purchase?.status === "failed" && <section className="wifi-failed"><XCircle size={26} /><p>Payment was not confirmed. Choose a package and try again.</p></section>}{message && <p className="wifi-message">{message}</p>}<footer>Jixels Technologies · Secure M-Pesa billing</footer></main>;
}
