import assert from "node:assert/strict";
import fs from "node:fs";

const read = file => fs.readFileSync(new URL(`../${file}`, import.meta.url), "utf8");
const app = read("App.js");
const config = read("src/config.js");
const session = read("src/services/session.js");
const payments = read("src/services/payments.js");
const tracking = read("src/services/tracking.js");
const apiFunction = read("supabase/functions/api/index.ts");
const financeApp = read("finance-portal/js/app.js");
const financeData = read("finance-portal/js/data.js");
const agentAuth = read("Jixels angets/src/services/auth.js");
const agentApp = read("Jixels angets/App.js");
const agentEas = JSON.parse(read("Jixels angets/eas.json"));
const eas = JSON.parse(read("eas.json"));
const adminVercelConfig = read("jixes/vercel.json");
const adminIndex = read("jixes/index.html");

assert.match(config, /\^https:/, "production transport must enforce HTTPS");
assert.equal(eas.build.production.env.EXPO_PUBLIC_DEMO_MODE, "false", "production must disable demo mode");
assert.equal(eas.build.production.env.EXPO_PUBLIC_JIXELS_API_URL, "https://tpzebfvhvjsezynqgdns.supabase.co/functions/v1/api", "customer production builds must point to the shared backend");
assert.equal(agentEas.build.production.env.EXPO_PUBLIC_JIXELS_AGENT_API_URL, "https://tpzebfvhvjsezynqgdns.supabase.co/functions/v1/api", "agent production builds must point to the shared backend");
assert.match(session, /if \(!session\.expiresAt\) return false/, "stored sessions must expire");
assert.match(payments, /Idempotency-Key/, "M-Pesa requests require an idempotency key");
assert.match(payments, /stable payment idempotency key is required/, "M-Pesa must reject missing idempotency keys");
assert.match(tracking, /socket\.on\("connect".*tracker:subscribe/, "tracker subscription must be connection-scoped");
assert.match(apiFunction, /function tramigoLocation/, "the API must normalize Tramigo location reports");
assert.match(apiFunction, /trackerStatus: tramigo\.trackerStatus/, "the API must pass Tramigo's explicit online state to the live-map client");
assert.match(apiFunction, /\/api\/v2\/devices\?page=1&per_page=1000/, "Tramigo IMEIs must be resolved through the documented device catalogue before requesting locations");
assert.match(apiFunction, /tramigoCloudDeviceId\(deviceId, deviceCatalogue, providerSession\)/, "Operations tracker refresh must use Tramigo's Cloud Device_ID");
assert.match(apiFunction, /route === "\/v1\/admin\/trackers\/refresh"/, "Operations must be able to refresh Tramigo tracker health server-side");
assert.match(apiFunction, /tramigo_device_id/, "Operations tracker refresh must use the configured Tramigo device ID");
assert.match(apiFunction, /\^\\d\{10,20\}\$/, "Operations may use a numeric tracker identifier as the Tramigo device ID");
assert.match(apiFunction, /reportAge.*10 \* 60_000/s, "Operations must fall back to a recent Tramigo report when no explicit device state is supplied");
assert.match(apiFunction, /Unhandled API request error/, "unexpected API errors must be logged instead of returning an opaque server error");
assert.match(apiFunction, /claim_tracker_refresh/, "live tracker refreshes must have server-side concurrency protection");
assert.match(apiFunction, /TRACKER_BATCH_TOO_LARGE/, "tracker refreshes must have a bounded batch size");
assert.match(apiFunction, /async function tramigoSession/, "a fleet refresh must reuse one Tramigo provider session");
assert.match(app, /verifyApprovalCode\(\{ email: applicant\.email, code \}\)/, "approval code verification must be bound to the registered customer email");
assert.match(apiFunction, /customer_approval_codes/, "approval codes must be stored server-side");
assert.match(apiFunction, /issueCustomerApprovalCode\(admin, account\.id, account\.email/, "account approval must issue the customer app approval code");
assert.match(apiFunction, /CUSTOMER_OTP_REQUIRED/, "customer access must remain blocked until the approval code is verified");
assert.match(apiFunction, /async function saveCustomerPushToken/, "pending customer registrations must persist or refresh the registered device token");
assert.match(apiFunction, /ticket\?\.status === "ok"/, "approval delivery must verify Expo push tickets instead of assuming an HTTP success delivered the notification");
assert.match(apiFunction, /Your verification code is \$\{code\}/, "the approval notification must visibly include the six-digit code");
assert.match(app, /function ApprovalNotification/, "the customer app must render its own approval notification screen");
assert.match(app, /setPhase\("approval-notice"\)/, "a received approval notification must open before dashboard access");
assert.match(app, /getLastNotificationResponseAsync/, "tapping an approval notification from a closed app must restore the in-app code screen");
assert.match(apiFunction, /async function signedScreeningDocuments/, "the admin must receive signed document image URLs");
assert.match(apiFunction, /screeningUpdateMatch/, "the admin must be able to update customer details and identity images");
assert.match(adminVercelConfig, /img-src[^\"]+https:\/\/\*\.supabase\.co/, "production CSP must permit authorized Supabase Storage identity images");
assert.match(adminIndex, /img-src[^\"]+https:\/\/\*\.supabase\.co/, "the portal CSP fallback must permit authorized Supabase Storage identity images");

const reportAction = app.match(/const action = \{[^;]+reportType: "payments"[^;]+\};/)?.[0] ?? "";
assert.ok(reportAction, "payment report request must exist");
assert.doesNotMatch(reportAction, /customerId|email:/, "report ownership must come from the access token");

const agentRegisterIndex = apiFunction.indexOf('route === "/v1/agent/auth/register"');
const agentResetIndex = apiFunction.indexOf('route === "/v1/agent/auth/request-password-reset"');
const authGateIndex = apiFunction.indexOf("const { data: identity } = await client.auth.getUser()");
assert.ok(agentRegisterIndex > 0 && agentRegisterIndex < authGateIndex, "agent registration must remain public before the auth gate");
assert.ok(agentResetIndex > 0 && agentResetIndex < authGateIndex, "agent password reset must remain public before the auth gate");
assert.match(apiFunction, /route === "\/v1\/auth\/account-status"/, "customer account status polling route must exist");
assert.match(apiFunction, /resetPasswordForEmail/, "password reset must use Supabase Auth");
assert.match(agentAuth, /\/v1\/agent\/auth\/login/, "agent app login must use the shared agent auth route");
assert.match(agentAuth, /\/v1\/agent\/auth\/register/, "agent app registration must use the shared agent auth route");
assert.match(apiFunction, /matchingCustomers.*\.eq\("email", email\)/s, "admin deletion must resolve agent-onboarded customer records by registered email");
assert.match(apiFunction, /removeCustomerWorkspace\(admin, customerId\)/, "admin deletion must remove every linked customer workspace");
assert.match(app, /Account removed/, "the customer app must clear and exit when its deleted account is no longer available");
assert.match(app, /setPhase\("gps"\)/, "a successful customer login must show the moving tracker activity screen before the dashboard");
assert.match(agentApp, /setInterval\(\(\) => refresh\(\{ showSpinner: false \}\), 5_000\)/, "the agent app must promptly refresh live customer records after admin deletion");
assert.match(agentApp, /setCustomers\(\[\]\)/, "the agent app must clear customer records when its access is revoked");
assert.match(financeApp, /commissionRules\(\)/, "Finance commission calculations must use saved rules");
assert.match(financeData, /saleCommission: ""/, "Finance must not invent a sale commission default");
assert.doesNotMatch(financeApp, /SALE_COMMISSION|MONTHLY_CUSTOMER_COMMISSION|KES 500 per sale|KES 50 per customer/, "Finance must not contain fixed commission values");

console.log("PASS production HTTPS and demo-mode policy");
console.log("PASS shared backend release URL policy");
console.log("PASS expiring secure-session policy");
console.log("PASS in-app approval-code binding");
console.log("PASS M-Pesa idempotency contract");
console.log("PASS connection-scoped tracker subscription contract");
console.log("PASS token-derived report ownership contract");
console.log("PASS public agent auth route contract");
