-- Approval codes are generated by the API and delivered only through the
-- registered customer app notification. The database stores a digest, never
-- the usable code itself.
create table if not exists public.customer_approval_codes (
  customer_id uuid primary key references public.profiles(id) on delete cascade,
  code_hash text not null,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.customer_approval_codes enable row level security;

notify pgrst, 'reload schema';
